name: azure_test
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # UI
  url_launcher: ^5.7.10
  fluttertoast: ^8.0.7
  flutter_easyloading: ^3.0.3


  # Core
  bloc: ^6.1.3
  flutter_bloc: ^6.1.3
  # hydrated_bloc: ^6.1.0
  equatable: ^1.2.5
  get_it: ^3.1.0
  dartz: ^0.9.2
  intl: ^0.17.0
  responsive_sizer: ^3.0.4+4

  dio: ^3.0.10
  dio_http_cache: ^0.2.11
  pretty_dio_logger: ^1.1.1
  data_connection_checker: ^0.3.4
  shared_preferences: 0.5.12+4
  flutter_session: ^0.1.1
  jwt_decode: ^0.3.1



  # Utils
  change_app_package_name: ^1.0.0
  # flutter pub run change_app_package_name:main <com.new.package.name>

  flutter_launcher_icons: ^0.8.1 # #^0.9.0
  # flutter pub run flutter_launcher_icons:main

  flutter_native_splash: ^0.3.0 # #^1.2.0
  # flutter pub run flutter_native_splash:create

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  bloc_test: 
flutter:
  uses-material-design: true

  assets:
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
